### ISSUE TITLE
Can't find self.__WB_MANIFEST in your SW source

### ISSUE THREAD

**Issue by xueyou2000** [Clarkkkk/workbox-rspack-plugin#7]
```ts
      new InjectManifest({
        swSrc: join(__dirname, `../src/locals/${local}/sw.ts`),
        swDest: `${local}/${local}-sw.js`
      })
```

使用InjectManifest插件在编译时提示找不到 self.__WB_MANIFEST, 但是 self.__WB_MANIFEST 应该是workbox自动注入的

**Comment by xueyou2000** [comment]
找到问题所在，sw.ts 文件中有代码报错导致编译失败，dist编译内容为空。所以匹配不到。解决后又有另一个问题

error   Failed to build.
error   TypeError: Cannot destructure property 'name' of 'rspackConfigs[index]' as it is undefined.
    at printTime (file:///home/xueyou/playground/i18n-framework-template/node_modules/.pnpm/@rsbuild+core@1.0.8/node_modules/@rsbuild/core/dist/index.js:6856:17)
    at file:///home/xueyou/playground/i18n-framework-template/node_modules/.pnpm/@rsbuild+core@1.0.8/node_modules/@rsbuild/core/dist/index.js:6865:11
    at Array.forEach (<anonymous>)
    at done (file:///home/xueyou/playground/i18n-framework-template/node_modules/.pnpm/@rsbuild+core@1.0.8/node_modules/@rsbuild/core/dist/index.js:6864:28)
    at Object.fn (file:///home/xueyou/playground/i18n-framework-template/node_modules/.pnpm/@rsbuild+core@1.0.8/node_modules/@rsbuild/core/dist/index.js:6883:7)
    at next (/home/xueyou/playground/i18n-framework-template/node_modules/.pnpm/@rspack+lite-tapable@1.0.1/node_modules/@rspack/lite-tapable/dist/index.js:523:25)
    at AsyncSeriesHook.callAsyncStageRange (/home/xueyou/playground/i18n-framework-template/node_modules/.pnpm/@rspack+lite-tapable@1.0.1/node_modules/@rspack/lite-tapable/dist/index.js:543:9)
    at AsyncSeriesHook.callAsync (/home/xueyou/playground/i18n-framework-template/node_modules/.pnpm/@rspack+lite-tapable@1.0.1/node_modules/@rspack/lite-tapable/dist/index.js:82:21)
    at /home/xueyou/playground/i18n-framework-template/node_modules/.pnpm/@rspack+core@1.0.8_@swc+helpers@0.5.13/node_modules/@rspack/core/dist/Compiler.js:318:41
    at /home/xueyou/playground/i18n-framework-template/node_modules/.pnpm/@rspack+core@1.0.8_@swc+helpers@0.5.13/node_modules/@rspack/core/dist/Compiler.js:462:28
    at done (/home/xueyou/playground/i18n-framework-template/node_modules/.pnpm/@rspack+lite-tapable@1.0.1/node_modules/@rspack/lite-tapable/dist/index.js:473:13)
    at AsyncSeriesHook.callAsyncStageRange (/home/xueyou/playground/i18n-framework-template/node_modules/.pnpm/@rspack+lite-tapable@1.0.1/node_modules/@rspack/lite-tapable/dist/index.js:480:20)
    at AsyncSeriesHook.callAsync (/home/xueyou/playground/i18n-framework-template/node_modules/.pnpm/@rspack+lite-tapable@1.0.1/node_modules/@rspack/lite-tapable/dist/index.js:82:21)
    at /home/xueyou/playground/i18n-framework-template/node_modules/.pnpm/@rspack+core@1.0.8_@swc+helpers@0.5.13/node_modules/@rspack/core/dist/Compiler.js:458:41
    at /home/xueyou/playground/i18n-framework-template/node_modules/.pnpm/@rspack+core@1.0.8_@swc+helpers@0.5.13/node_modules/@rspack/core/dist/Compiler.js:525:23

将 @rsbuild/core从 1.0.8 升级到 1.0.13 后，一切正常了
